<?php
//[STAMP] e9c950e9df1f947a38e0045b4d847c96

namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Scenario;

trait FunctionalTesterActions
{
    /**
     * @return Scenario
     */
    abstract protected function getScenario();
}
