<?php

use PHPUnit\Framework\Attributes\BackupGlobals;
use PHPUnit\Framework\Attributes\ExcludeGlobalVariableFromBackup;
use PHPUnit\Framework\TestCase;

class Checker extends TestCase {
    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        $keywordGlobal = 3;
    }

    #[BackupGlobals(true)]
    #[ExcludeGlobalVariableFromBackup('constantGlobal')]
    #[\PHPUnit\Framework\Attributes\Test]
    public function checkSmthg()
    {
        $GLOBALS['constantGlobal'] = 'global';
        self::assertEquals(2, $GLOBALS['constantGlobal']);
    }

    #[\PHPUnit\Framework\Attributes\Test]
    public function checkChanges()
    {
        self::assertEquals(3, $GLOBALS['constantGlobal']);
    }
}