<?php

//[STAMP] f0b5ff3d5b3913f549b99bb1b1f56089
// phpcs:ignoreFile

namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Helper\Functional::seeEqualNumbers()
     */
    public function seeEqualNumbers($a, $b)
    {
        return $this->getScenario()->runStep(new \Codeception\Step\Assertion('seeEqualNumbers', func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * [!] Conditional Assertion: Test won't be stopped on fail
     *
     * @see \Helper\Functional::seeEqualNumbers()
     */
    public function canSeeEqualNumbers($a, $b)
    {
        return $this->getScenario()->runStep(new \Codeception\Step\ConditionalAssertion('seeEqualNumbers', func_get_args()));
    }
}
